/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tasktrove.view;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;
import tasktrove.controller.HomeController;
import tasktrove.model.User;
import tasktrove.config.Database;

/**
 *
 * @author riakgu
 */
public class HomeView extends javax.swing.JPanel {

    private HomeController hc = new HomeController();
    
    String[] columnNames = {"Task Id","Task Name", "Description", "Started", "Deadline", "Status"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0); 

    /**
     * Creates new form HomeView
     */
    public HomeView(User user) {
        initComponents();

        // Menampilkan deadline hari ini pada tabel
        hc.deadlineToday(model, user.getUser_id());

        // Menetapkan jumlah tugas yang belum selesai ke jLabel6
        jLabel6.setText(Integer.toString(hc.getUndoneTasks(user.getUser_id())));

        // Menetapkan total jumlah tugas ke jLabel7
        jLabel7.setText(Integer.toString(hc.getTotalTasks(user.getUser_id())));

        // Mengatur warna latar belakang tabel, viewport, dan header tabel
        deadlineTodayTable.setBackground(new Color(242, 247, 255));
        jScrollPane1.getViewport().setBackground(new Color(242, 247, 255));
        deadlineTodayTable.getTableHeader().setBackground(new Color(242, 247, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        undoneBox = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalBox = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deadlineTodayTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(920, 585));
        setMinimumSize(new java.awt.Dimension(920, 585));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(920, 585));
        setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setMaximumSize(new java.awt.Dimension(920, 585));
        homePanel.setMinimumSize(new java.awt.Dimension(920, 585));
        homePanel.setOpaque(false);

        undoneBox.setBackground(new java.awt.Color(242, 247, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Undone Task");

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout undoneBoxLayout = new javax.swing.GroupLayout(undoneBox);
        undoneBox.setLayout(undoneBoxLayout);
        undoneBoxLayout.setHorizontalGroup(
            undoneBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(undoneBoxLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(undoneBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        undoneBoxLayout.setVerticalGroup(
            undoneBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(undoneBoxLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(25, 25, 25))
        );

        totalBox.setBackground(new java.awt.Color(242, 247, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Total Task");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout totalBoxLayout = new javax.swing.GroupLayout(totalBox);
        totalBox.setLayout(totalBoxLayout);
        totalBoxLayout.setHorizontalGroup(
            totalBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalBoxLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(totalBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        totalBoxLayout.setVerticalGroup(
            totalBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalBoxLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        deadlineTodayTable.setModel(model);
        deadlineTodayTable.setGridColor(new java.awt.Color(242, 247, 255));
        deadlineTodayTable.setSelectionBackground(new java.awt.Color(242, 247, 255));
        jScrollPane1.setViewportView(deadlineTodayTable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Deadline Today");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(homePanelLayout.createSequentialGroup()
                            .addComponent(undoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(undoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        add(homePanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable deadlineTodayTable;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel totalBox;
    private javax.swing.JPanel undoneBox;
    // End of variables declaration//GEN-END:variables

    private String String(int totalTask) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
